[package]
name = "device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.7.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
